multi order table sort added, data grouping with separators added, da…
Packet-Clearing-House/maptable pull request #129
Opened 2024-06-11 04:13 UTC by Anjalbaral

multi order table sort added, data grouping with separators added, data numbering for multi order sort added. @melalj

2024-06-11 15:01 UTC, melalj requested changes
The demo works, well done.

I would edit the naming for dataSN, and add the documentation on the README with the new options, and how to use it.

2024-06-12 04:56 UTC, Anjalbaral commented on docs/examples/table-with-multi-column-sort.html
> +        dataSN: { enabled: true },
SN is short form for Serial Number, I can change it to dataCount or dataCountIndicator.

2024-06-12 04:57 UTC, Anjalbaral commented on src/utils.js
> +const customSortOrders = {
Yeah, that will be better, will be updating this.

2024-06-12 10:35 UTC, melalj approved these changes

2024-06-12 10:36 UTC, merged